'use strict';

const entryTypes = {
  FILE_NAME_TYPE: 'FILE_NAME_TYPE',
  DIRECTORY_NAME_TYPE: 'DIRECTORY_NAME_TYPE',
  FILE_NAME_MARKER_TYPE: 'FILE_NAME_MARKER_TYPE',
  DIRECTORY_NAME_MARKER_TYPE: 'DIRECTORY_NAME_MARKER_TYPE'
};

module.exports = entryTypes;
