'use strict';

const NO_DRAGGING_WITHIN = 'NO_DRAGGING_WITHIN',
			NO_DRAGGING_SUB_ENTRIES = 'NO_DRAGGING_SUB_ENTRIES',
			NO_DRAGGING_INTO_SUB_DIRECTORIES = 'NO_DRAGGING_INTO_SUB_DIRECTORIES',
			REMOVE_EMPTY_PARENT_DIRECTORIES = 'REMOVE_EMPTY_PARENT_DIRECTORIES',
			ESCAPE_KEY_STOPS_DRAGGING = 'ESCAPE_KEY_STOPS_DRAGGING';

module.exports = {
	NO_DRAGGING_WITHIN,
	NO_DRAGGING_SUB_ENTRIES,
	NO_DRAGGING_INTO_SUB_DIRECTORIES,
	REMOVE_EMPTY_PARENT_DIRECTORIES,
	ESCAPE_KEY_STOPS_DRAGGING
};
