"use strict";

const FILE_NAME_TYPE = "FILE_NAME_TYPE",
      DIRECTORY_NAME_TYPE = "DIRECTORY_NAME_TYPE",
      FILE_NAME_MARKER_TYPE = "FILE_NAME_MARKER_TYPE",
      DIRECTORY_NAME_MARKER_TYPE = "DIRECTORY_NAME_MARKER_TYPE";

module.exports = {
  FILE_NAME_TYPE,
  DIRECTORY_NAME_TYPE,
  FILE_NAME_MARKER_TYPE,
  DIRECTORY_NAME_MARKER_TYPE
};
