"use strict";

export const NO_DRAGGING_WITHIN = "NO_DRAGGING_WITHIN";
export const NO_DRAGGING_SUB_ENTRIES = "NO_DRAGGING_SUB_ENTRIES";
export const NO_DRAGGING_INTO_SUB_DIRECTORIES = "NO_DRAGGING_INTO_SUB_DIRECTORIES";
export const REMOVE_EMPTY_PARENT_DIRECTORIES = "REMOVE_EMPTY_PARENT_DIRECTORIES";
export const ESCAPE_KEY_STOPS_DRAGGING = "ESCAPE_KEY_STOPS_DRAGGING";

export default {
  NO_DRAGGING_WITHIN,
  NO_DRAGGING_SUB_ENTRIES,
  NO_DRAGGING_INTO_SUB_DIRECTORIES,
  REMOVE_EMPTY_PARENT_DIRECTORIES,
  ESCAPE_KEY_STOPS_DRAGGING
};
